// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatikaHomework1.Models
{
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
    public partial class ProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}